markdown: kramdown
theme: minima

assets:
  assets:
    - 'images/*'
    - 'images/**/*'
    - 'js/application.js'
    - 'css/style.css'

  sources:
    - _assets

  compress:
    js:  true

gems:
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
